/** Full FAQ content for the /faq page, grouped by category. Source of truth. */

export interface FaqQA {
  q: string;
  a: string;
}

export interface FaqCategory {
  key: string;
  label: string;
  items: FaqQA[];
}

export const FAQ_CATEGORIES: FaqCategory[] = [
  {
    key: "general",
    label: "General",
    items: [
      { q: "What languages can I learn at Academy of Languages and Beyond (ALB)?", a: "Academy of Languages and Beyond (ALB) as of now primarily offers live online and recorded French, German and English language programmes; however, there are many other international languages yet to be made live on the platform. The programmes have structured learning pathways for all kinds of learners, be it beginners, intermediate or advanced students who want to brush up or need the sprint track. All the programmes at ALB follow CEFR recognised standards and combine language learning with regular communication, confidence building, and soft-skills modules." },
      { q: "Is Academy of Languages and Beyond (ALB) an online language institute?", a: "Yes. Academy of Languages and Beyond (ALB) is a live online language academy that helps students learn French, German, and English from anywhere. Unlike self-paced apps or recorded courses, ALB delivers interactive live classes where learners practise speaking, receive trainer feedback, participate in discussions, and build confidence through real conversations." },
      { q: "Can I learn a foreign language online successfully?", a: "Yes. Learning a foreign language online can be just as effective as classroom learning when it includes live instruction, regular speaking practice, and personalised feedback. Academy of Languages and Beyond (ALB) combines live classes, guided practice, assignments, mock assessments, and doubt support to help learners develop practical communication skills instead of simply memorising grammar rules." },
      { q: "Which foreign language should I learn for my career?", a: "The best foreign language depends on your career goals. French is valuable for international organisations, Canada immigration, hospitality, and diplomacy. German is widely recognised in engineering, manufacturing, research, and higher education. English remains the global language of business, technology, and international communication. Academy of Languages and Beyond (ALB) helps learners choose the right language based on their education, profession, and future aspirations." },
      { q: "Which foreign language is best for studying abroad?", a: "The ideal language depends on your destination country and academic plans. Students preparing for France, Belgium, Switzerland, or Canada often benefit from learning French, while those planning to study in Germany or Austria usually require German. English remains essential for universities across the UK, USA, Canada, Australia, and many international programmes worldwide. Academy of Languages and Beyond (ALB) offers guidance to help students choose the language that best supports their study abroad goals." },
      { q: "Is learning a foreign language worth it in India?", a: "Yes. Learning a foreign language can create opportunities for higher education, global careers, international business, immigration, tourism, and cross-cultural communication. Employers increasingly value multilingual professionals because they can work across international markets and communicate with diverse clients. Academy of Languages and Beyond (ALB) prepares learners not only for language proficiency but also for confident communication in global environments." },
      { q: "How long does it take to learn a foreign language?", a: "The time required depends on the language, your starting level, and how consistently you practise. Most learners progress through internationally recognised CEFR levels such as A1, A2, B1, and B2 over several months of structured learning. Academy of Languages and Beyond (ALB) follows a level-based curriculum that helps students build speaking, listening, reading, and writing skills progressively." },
      { q: "Can adults learn a new language successfully?", a: "Absolutely. Adults can successfully learn a new language with the right teaching approach and consistent practice. While children may acquire languages differently, adults often learn faster because they can apply logical thinking, existing vocabulary, and real-life experiences. Academy of Languages and Beyond (ALB) designs its programmes for both students and working professionals, making language learning practical and achievable at any age." },
      { q: "Is it difficult to learn a foreign language?", a: "Learning a new language requires consistency, but it does not have to be difficult. Many learners struggle because they focus only on grammar and vocabulary without enough speaking practice. Academy of Languages and Beyond (ALB) uses live conversations, interactive activities, pronunciation coaching, and practical communication exercises to make language learning more natural and enjoyable." },
      { q: "What is the CEFR language level system?", a: "The Common European Framework of Reference for Languages (CEFR) is the international standard used to measure language proficiency. It divides language learning into six levels: A1, A2, B1, B2, C1, and C2. Academy of Languages and Beyond (ALB) structures its language programmes around these internationally recognised levels, helping learners track their progress and prepare for global certifications." },
      { q: "Can I become fluent by learning a language online?", a: "Yes, fluency is possible through online learning when your programme emphasises regular speaking practice, personalised feedback, and consistent interaction. Academy of Languages and Beyond (ALB) focuses on helping learners actively use the language through live conversations, classroom discussions, role plays, and communication-based activities rather than relying only on recorded lessons or self-study." },
      { q: "Are online language classes as effective as offline classes?", a: "Yes. Live online language classes can be as effective as traditional classroom learning when they provide real-time interaction, structured lessons, and opportunities to practise speaking. Academy of Languages and Beyond (ALB) offers live instructor-led classes, continuous assessments, speaking exercises, and doubt support to create an engaging learning experience from anywhere." },
      { q: "Do I need any prior knowledge before joining Academy of Languages and Beyond (ALB)?", a: "No. Academy of Languages and Beyond (ALB) offers programmes for complete beginners as well as learners with previous language experience. Before joining, students receive guidance to identify the most suitable starting level based on their current proficiency and learning goals." },
      { q: "Which foreign language is easiest to learn?", a: "There is no single easiest language because learning difficulty depends on your native language, previous experience, and personal motivation. However, with structured teaching and regular speaking practice, languages such as French, German, and English become significantly easier to master. Academy of Languages and Beyond (ALB) simplifies language learning through practical instruction, interactive classes, and progressive skill development." },
      { q: "Why should I learn a foreign language instead of using translation apps?", a: "Translation apps are useful for understanding words and simple phrases, but they cannot replace genuine communication, cultural understanding, or professional conversations. Learning a language helps you think, respond, and interact naturally without depending on technology. Academy of Languages and Beyond (ALB) helps learners build lasting communication skills that can be applied in interviews, universities, workplaces, travel, and everyday life." },
    ],
  },
  {
    key: "about",
    label: "About ALB",
    items: [
      { q: "What is Academy of Languages and Beyond (ALB)?", a: "Academy of Languages and Beyond (ALB) is a live online language and communication academy that helps students, professionals, and young learners develop practical language skills for real-world success. Along with internationally recognised French, German, and English programmes, ALB also focuses on communication, confidence, and professional development through its signature +Beyond Global Confidence Programme, preparing learners for careers, higher education, immigration, and global opportunities." },
      { q: "What makes Academy of Languages and Beyond (ALB) different from other language institutes?", a: "Academy of Languages and Beyond (ALB) goes beyond traditional language teaching by combining language proficiency with communication skills, confidence building, and professional readiness. Instead of focusing only on grammar and examinations, ALB prepares learners to use their language skills in interviews, presentations, workplaces, universities, and everyday conversations. Every programme is designed around practical application, not just certification." },
      { q: "Why should I choose Academy of Languages and Beyond (ALB)?", a: "Academy of Languages and Beyond (ALB) offers structured, live online language programmes taught by experienced trainers using internationally recognised learning frameworks. Students benefit from interactive classes, regular speaking practice, doubt support, class recordings, and the unique +Beyond Global Confidence Programme, helping them build communication skills alongside language proficiency." },
      { q: "Does Academy of Languages and Beyond (ALB) offer live online classes?", a: "Yes. Every course at Academy of Languages and Beyond (ALB) is taught through live online classes led by experienced instructors. Students actively participate in discussions, speaking activities, role plays, and classroom exercises while receiving immediate feedback from their trainer. This interactive learning environment helps learners build confidence much faster than self-paced learning alone." },
      { q: "Does Academy of Languages and Beyond (ALB) provide recorded lectures?", a: "Yes. Academy of Languages and Beyond (ALB) provides class recordings to enrolled students whenever available. These recordings are especially useful for learners who miss a class due to work, college, travel, or personal commitments. Students can revisit previous lessons at their convenience, revise important concepts, and continue progressing without falling behind." },
      { q: "Does Academy of Languages and Beyond (ALB) offer a free demo class?", a: "Yes. Academy of Languages and Beyond (ALB) offers a free live demo class so prospective learners can experience the teaching methodology before enrolling. During the demo, students interact with trainers, participate in classroom activities, and understand how ALB's live online learning approach differs from recorded or self-paced courses." },
      { q: "Does Academy of Languages and Beyond (ALB) provide doubt support outside class?", a: "Yes. Academy of Languages and Beyond (ALB) believes learning continues beyond the classroom. Students receive academic support for clearing doubts, revisiting concepts, and strengthening their understanding between classes. This ensures learners remain confident and continue progressing throughout their language journey." },
      { q: "Does Academy of Languages and Beyond (ALB) provide course completion certificates?", a: "Yes. Academy of Languages and Beyond (ALB) awards course completion certificates to learners who successfully complete their programme requirements. Students preparing for internationally recognised examinations such as DELF, Goethe, IELTS, TEF, or TCF are also guided toward the certification that aligns with their academic, immigration, or career goals." },
      { q: "Are Academy of Languages and Beyond (ALB) trainers qualified to teach foreign languages?", a: "Yes. Academy of Languages and Beyond (ALB) works with experienced language trainers who combine subject expertise with practical teaching methodologies. In addition to helping students develop language proficiency, ALB instructors focus on improving pronunciation, communication confidence, and real-world language application through interactive learning experiences." },
      { q: "Does Academy of Languages and Beyond (ALB) only prepare students for language exams?", a: "No. While Academy of Languages and Beyond (ALB) prepares students for internationally recognised language certifications, the primary focus is helping learners communicate confidently in real-world situations. Every programme balances exam preparation with speaking practice, communication skills, confidence building, and practical language use." },
      { q: "Does Academy of Languages and Beyond (ALB) include soft skills with every programme?", a: "Yes. One of the biggest differentiators of Academy of Languages and Beyond (ALB) is the integration of communication and professional development through the +Beyond Global Confidence Programme. Learners develop presentation skills, interview readiness, workplace communication, public speaking, and confidence alongside their language training, preparing them for success beyond the classroom." },
      { q: "Can I study from anywhere with Academy of Languages and Beyond (ALB)?", a: "Yes. Since all programmes at Academy of Languages and Beyond (ALB) are conducted online, learners can attend classes from anywhere with a stable internet connection. This flexibility allows students, working professionals, and international learners to continue learning regardless of their location." },
      { q: "Does Academy of Languages and Beyond (ALB) teach children, students, and working professionals?", a: "Yes. Academy of Languages and Beyond (ALB) offers specialised programmes for children, university students, working professionals, and individuals preparing for higher education, careers, immigration, or personal development. Each programme is designed according to the learner's age, goals, and learning requirements." },
      { q: "What does the name \"Academy of Languages and Beyond\" mean?", a: "The name Academy of Languages and Beyond (ALB) reflects the academy's belief that learning a language is only the beginning. Beyond language proficiency, ALB focuses on communication, confidence, cultural awareness, professional development, and lifelong learning. Every programme is designed to prepare learners not just to pass an exam, but to succeed in real-world academic, personal, and professional environments." },
      { q: "Is Academy of Languages and Beyond (ALB) suitable for complete beginners?", a: "Absolutely. Academy of Languages and Beyond (ALB) welcomes learners with no prior knowledge of French, German, or English. Beginner-friendly programmes start with the fundamentals before gradually building vocabulary, grammar, pronunciation, speaking confidence, and communication skills through structured live instruction." },
    ],
  },
  {
    key: "admissions",
    label: "Admissions & Learning",
    items: [
      { q: "How do I enrol at Academy of Languages and Beyond (ALB)?", a: "Enrolling at Academy of Languages and Beyond (ALB) is simple. You can book a free demo class, speak with an academic advisor, discuss your learning goals, and receive guidance on selecting the right programme and starting level. Once enrolled, you'll receive all the information needed to begin your learning journey." },
      { q: "Does Academy of Languages and Beyond (ALB) offer flexible class timings?", a: "Yes. Academy of Languages and Beyond (ALB) offers multiple batch options whenever possible to accommodate students, working professionals, and learners with different schedules. Batch availability may vary depending on the programme and level." },
      { q: "Can I switch my batch after enrolling?", a: "Yes, subject to seat availability. Academy of Languages and Beyond (ALB) understands that work schedules, academic commitments, and personal circumstances may change. Students can request a batch transfer, and the academic team will assist wherever possible." },
      { q: "What happens if I miss a live class at Academy of Languages and Beyond (ALB)?", a: "If you miss a live class, Academy of Languages and Beyond (ALB) provides access to the class recording whenever available, allowing you to catch up at your convenience. Students can also reach out for doubt support to ensure they continue progressing confidently." },
      { q: "Does Academy of Languages and Beyond (ALB) provide study material?", a: "Yes. Academy of Languages and Beyond (ALB) provides structured learning material, classroom resources, assignments, and practice exercises aligned with each programme's curriculum. Additional resources may also be recommended depending on the learner's goals and certification pathway." },
      { q: "How are students assessed at Academy of Languages and Beyond (ALB)?", a: "Academy of Languages and Beyond (ALB) assesses students through quizzes, assignments, speaking activities, classroom participation, mock assessments, and periodic evaluations. These assessments help learners track their progress and identify areas for improvement throughout the programme." },
      { q: "Does Academy of Languages and Beyond (ALB) give homework and practice assignments?", a: "Yes. Regular assignments and practice activities form an important part of learning at Academy of Languages and Beyond (ALB). These exercises reinforce classroom learning, improve retention, and encourage students to practise speaking, writing, reading, and listening outside class." },
      { q: "How much speaking practice will I receive during classes?", a: "Speaking practice is integrated into every programme at Academy of Languages and Beyond (ALB). Students participate in conversations, role plays, pronunciation exercises, discussions, and interactive classroom activities designed to build fluency and confidence through regular language use." },
      { q: "Can I join Academy of Languages and Beyond (ALB) if I have no previous language experience?", a: "Yes. Academy of Languages and Beyond (ALB) offers beginner-friendly programmes designed specifically for learners with no prior knowledge. Trainers introduce concepts step by step, helping students gradually build confidence while developing practical communication skills." },
      { q: "Does Academy of Languages and Beyond (ALB) provide academic guidance if I don't know which course to choose?", a: "Yes. Before enrolling, Academy of Languages and Beyond (ALB) helps learners understand the available programmes and recommends the most suitable course based on their goals, current proficiency, career plans, and future aspirations." },
      { q: "Can I speak to someone before enrolling?", a: "Absolutely. Academy of Languages and Beyond (ALB) encourages prospective learners to connect with its academic team before enrolling. This conversation helps answer questions about courses, learning pathways, certifications, schedules, and programme suitability." },
      { q: "Why does Academy of Languages and Beyond (ALB) focus so much on communication?", a: "Academy of Languages and Beyond (ALB) believes that true language learning is measured by the ability to communicate confidently, not simply by passing examinations. Every programme therefore combines structured language instruction with speaking practice, interactive activities, and the +Beyond Global Confidence Programme, ensuring learners can use their skills effectively in academic, professional, and everyday situations." },
    ],
  },
  {
    key: "french",
    label: "French Programme",
    items: [
      { q: "Can I learn French online through Academy of Languages and Beyond (ALB)?", a: "Yes. Academy of Languages and Beyond (ALB) offers live online French language courses designed for beginners as well as advanced learners. Every class is interactive and focuses on speaking, listening, reading, and writing, helping students build practical communication skills while preparing for higher education, immigration, global careers, or international certifications." },
      { q: "Is French worth learning in 2026?", a: "Yes. French remains one of the world's most valuable international languages. It is spoken across multiple continents and is widely used in international business, diplomacy, education, tourism, and immigration. Academy of Languages and Beyond (ALB) helps learners develop practical French language skills that open opportunities for study abroad, career advancement, and global mobility." },
      { q: "Can French help me immigrate to Canada?", a: "Yes. French language proficiency can strengthen immigration profiles for certain Canadian immigration pathways and may provide additional advantages under specific government programmes. Academy of Languages and Beyond (ALB) prepares learners for internationally recognised French language examinations such as TEF and TCF while helping them develop practical communication skills for life in French-speaking environments." },
      { q: "Which French certification should I choose: DELF, TEF or TCF?", a: "The right certification depends on your goal. DELF is commonly chosen for academic progression and internationally recognised proof of French proficiency. TEF and TCF are frequently required for immigration, particularly for Canada. Academy of Languages and Beyond (ALB) helps learners understand the purpose of each exam and recommends the certification that best aligns with their education, career, or immigration plans." },
      { q: "Does Academy of Languages and Beyond (ALB) prepare students for DELF?", a: "Yes. Academy of Languages and Beyond (ALB) follows a CEFR-based curriculum that prepares learners for DELF examinations from beginner to advanced levels. Students develop balanced language skills through live instruction, speaking practice, mock assessments, and structured exam preparation." },
      { q: "What French levels does Academy of Languages and Beyond (ALB) offer?", a: "Academy of Languages and Beyond (ALB) offers French language programmes aligned with the Common European Framework of Reference for Languages (CEFR). Learners progress through internationally recognised levels such as A1, A2, B1, and B2, building speaking, listening, reading, and writing skills systematically." },
      { q: "Is French difficult for Indian learners?", a: "French may seem unfamiliar at first, but it becomes much easier with structured learning and regular speaking practice. Academy of Languages and Beyond (ALB) introduces grammar, pronunciation, and vocabulary gradually through practical conversations and interactive classroom activities, making French accessible for learners of all backgrounds." },
      { q: "Can I learn French without any previous knowledge?", a: "Absolutely. Academy of Languages and Beyond (ALB) offers beginner-friendly French programmes designed for learners with no prior experience. Students start with pronunciation, basic vocabulary, greetings, sentence formation, and everyday communication before progressing to higher proficiency levels." },
      { q: "How long does it take to become conversational in French?", a: "The timeline depends on your consistency, learning goals, and starting level. Most learners begin holding simple conversations after completing the beginner levels with regular practice. Academy of Languages and Beyond (ALB) focuses on practical speaking from the beginning, helping learners gain confidence alongside grammar and vocabulary." },
      { q: "Can learning French improve my career opportunities?", a: "Yes. French is valued across industries such as hospitality, aviation, international business, luxury retail, customer support, diplomacy, and education. Multilingual professionals often have access to wider career opportunities in both India and international markets. Academy of Languages and Beyond (ALB) prepares learners for professional communication as well as language proficiency." },
      { q: "Can I study in France after learning French at Academy of Languages and Beyond (ALB)?", a: "Yes. Many universities in France and other French-speaking regions require proof of French language proficiency depending on the programme. Academy of Languages and Beyond (ALB) helps learners progress through internationally recognised CEFR levels and prepares them for certifications commonly accepted by educational institutions." },
      { q: "Why should I learn French instead of another foreign language?", a: "French is one of the most widely taught international languages and offers opportunities across education, immigration, diplomacy, international organisations, tourism, and business. Academy of Languages and Beyond (ALB) helps learners choose French when it aligns with their long-term academic, professional, or personal goals." },
    ],
  },
  {
    key: "german",
    label: "German Programme",
    items: [
      { q: "Can I learn German online through Academy of Languages and Beyond (ALB)?", a: "Yes. Academy of Languages and Beyond (ALB) offers live online German language courses for beginners and advanced learners. The curriculum combines structured grammar instruction with speaking practice, listening exercises, reading comprehension, and real-world communication to help students become confident German speakers." },
      { q: "Is German worth learning in 2026?", a: "Yes. German continues to be one of Europe's most valuable languages for higher education, engineering, technology, manufacturing, healthcare, and research. Learning German can create opportunities for studying, working, or living in Germany, Austria, Switzerland, and other German-speaking regions. Academy of Languages and Beyond (ALB) prepares learners for both language proficiency and practical communication." },
      { q: "Can learning German help me study in Germany?", a: "Yes. Many universities in Germany offer programmes that either require or strongly recommend German language proficiency. Learning German also helps students adapt more comfortably to everyday life, internships, and employment opportunities. Academy of Languages and Beyond (ALB) provides structured German learning pathways aligned with internationally recognised proficiency levels." },
      { q: "Does Academy of Languages and Beyond (ALB) prepare students for Goethe examinations?", a: "Yes. Academy of Languages and Beyond (ALB) prepares learners for Goethe examinations through CEFR-aligned German language training. Students receive structured instruction, speaking practice, mock assessments, and guidance to build confidence before appearing for internationally recognised German language certifications." },
      { q: "Which German certification should I choose?", a: "The appropriate German certification depends on your goals. Goethe certificates are widely recognised internationally, while exams such as TestDaF are often required for admission to German universities. Academy of Languages and Beyond (ALB) helps learners choose the certification that best supports their education, career, or immigration plans." },
      { q: "What German levels does Academy of Languages and Beyond (ALB) offer?", a: "Academy of Languages and Beyond (ALB) offers German programmes structured around the CEFR framework, including A1, A2, B1, and B2 levels. Each stage builds progressively on grammar, vocabulary, pronunciation, speaking, reading, writing, and listening skills." },
      { q: "Is German difficult to learn?", a: "German has a structured grammar system that becomes easier to understand through consistent practice and expert guidance. Academy of Languages and Beyond (ALB) simplifies complex concepts using practical examples, interactive learning, and regular speaking activities that help learners gain confidence step by step." },
      { q: "Can I learn German without any previous knowledge?", a: "Yes. Academy of Languages and Beyond (ALB) welcomes complete beginners. Students begin with foundational vocabulary, pronunciation, greetings, sentence construction, and everyday conversations before progressing to higher proficiency levels." },
      { q: "How long does it take to become conversational in German?", a: "The time required depends on your learning pace, consistency, and practice. Learners who attend classes regularly and actively participate in speaking activities often develop conversational skills during the beginner and intermediate levels. Academy of Languages and Beyond (ALB) encourages continuous communication practice throughout the programme." },
      { q: "Can German improve my career opportunities?", a: "Yes. German is highly valued in industries such as engineering, automotive manufacturing, healthcare, information technology, research, and international business. Professionals with German language skills often gain access to wider employment opportunities in Europe and multinational organisations. Academy of Languages and Beyond (ALB) prepares learners for these opportunities through practical language training." },
      { q: "Is German useful outside Germany?", a: "Yes. German is spoken not only in Germany but also in Austria, Switzerland, Liechtenstein, Luxembourg, and parts of Belgium. It is one of Europe's most widely spoken native languages and plays an important role in international business, science, engineering, and higher education. Academy of Languages and Beyond (ALB) helps learners develop skills that are valuable across German-speaking regions." },
      { q: "Why should I learn German through Academy of Languages and Beyond (ALB)?", a: "Academy of Languages and Beyond (ALB) combines structured CEFR-based German language training with live online classes, practical speaking practice, academic support, and communication-focused learning. In addition to preparing learners for internationally recognised certifications, ALB helps students build the confidence to use German effectively in academic, professional, and everyday situations." },
    ],
  },
  {
    key: "english",
    label: "English Programme",
    items: [
      { q: "Can I learn English online through Academy of Languages and Beyond (ALB)?", a: "Yes. Academy of Languages and Beyond (ALB) offers live online English language programmes designed for students, working professionals, job seekers, and anyone looking to improve their communication skills. Every class is interactive and focuses on speaking, listening, reading, writing, and real-world communication rather than memorisation." },
      { q: "Does Academy of Languages and Beyond (ALB) offer spoken English classes?", a: "Yes. Spoken English is an integral part of every English programme at Academy of Languages and Beyond (ALB). Learners participate in conversations, discussions, role plays, presentations, and practical speaking activities that help them communicate naturally and confidently in everyday, academic, and professional situations." },
      { q: "Can Academy of Languages and Beyond (ALB) help me improve my spoken English confidence?", a: "Yes. Many learners understand English but hesitate to speak because they lack confidence rather than knowledge. Academy of Languages and Beyond (ALB) focuses on building speaking confidence through live conversations, personalised feedback, pronunciation coaching, and practical communication exercises that encourage learners to speak from the very beginning." },
      { q: "Does Academy of Languages and Beyond (ALB) prepare students for IELTS?", a: "Yes. Academy of Languages and Beyond (ALB) offers structured IELTS preparation covering Listening, Reading, Writing, and Speaking. Students receive exam strategies, mock assessments, personalised feedback, and communication practice designed to help them achieve their target IELTS band score." },
      { q: "Can I join Academy of Languages and Beyond (ALB) if my English is very weak?", a: "Absolutely. Academy of Languages and Beyond (ALB) offers beginner-friendly English programmes for learners who have little confidence in speaking or communicating in English. The curriculum starts with the fundamentals before gradually developing fluency, pronunciation, grammar, vocabulary, and communication skills." },
      { q: "How long does it take to improve spoken English?", a: "The timeline depends on your current level, consistency, and practice. Most learners begin noticing improvements in confidence, vocabulary, and communication within the first few months of regular learning. Academy of Languages and Beyond (ALB) follows a structured progression that helps students improve steadily through continuous speaking practice and trainer feedback." },
      { q: "Does Academy of Languages and Beyond (ALB) teach Business English?", a: "Yes. Academy of Languages and Beyond (ALB) includes workplace communication, professional vocabulary, presentation skills, meeting etiquette, email writing, and business conversations within its advanced English programmes. These skills help learners communicate confidently in corporate and professional environments." },
      { q: "Can Academy of Languages and Beyond (ALB) help me prepare for job interviews?", a: "Yes. Interview preparation is an important part of the learning experience at Academy of Languages and Beyond (ALB). Learners practise answering interview questions, introducing themselves professionally, communicating confidently, and presenting their ideas clearly. These skills are further strengthened through the +Beyond Global Confidence Programme." },
      { q: "Is Academy of Languages and Beyond (ALB)'s English programme suitable for working professionals?", a: "Yes. Academy of Languages and Beyond (ALB) designs its English programmes for students as well as working professionals who want to improve communication, prepare for interviews, advance their careers, or work confidently in international environments. Flexible online learning and recorded sessions help busy professionals stay consistent." },
      { q: "What's the difference between spoken English and Business English?", a: "Spoken English focuses on everyday communication, fluency, pronunciation, and confidence in conversations. Business English builds on these foundations by introducing workplace communication, meetings, presentations, professional emails, client interactions, and formal business vocabulary. Academy of Languages and Beyond (ALB) helps learners develop both depending on their goals." },
      { q: "Will Academy of Languages and Beyond (ALB) help me improve my grammar?", a: "Yes. Grammar is taught as a practical communication tool rather than through rote memorisation. Academy of Languages and Beyond (ALB) helps learners apply grammar naturally during speaking, writing, and everyday conversations so they develop both accuracy and confidence." },
      { q: "Why do I understand English but struggle to speak it?", a: "Many learners spend years reading and studying English without getting enough opportunities to practise speaking. Academy of Languages and Beyond (ALB) addresses this gap through regular conversations, pronunciation practice, role plays, discussions, and live interaction, helping learners convert passive knowledge into confident communication." },
      { q: "Can Academy of Languages and Beyond (ALB) help me improve my pronunciation?", a: "Yes. Pronunciation is an essential part of every English programme at Academy of Languages and Beyond (ALB). Trainers provide continuous feedback on pronunciation, clarity, intonation, and natural speech patterns to help learners communicate confidently and effectively." },
      { q: "Is English enough for career growth today?", a: "Strong English communication remains one of the most valuable professional skills worldwide. However, employers increasingly look beyond language proficiency to communication, collaboration, presentation, and leadership abilities. That is why Academy of Languages and Beyond (ALB) combines English language learning with communication and soft skills through its +Beyond Global Confidence Programme." },
      { q: "Why should I learn English through Academy of Languages and Beyond (ALB)?", a: "Academy of Languages and Beyond (ALB) offers much more than a traditional spoken English course. Learners develop fluency, communication skills, interview readiness, presentation confidence, workplace communication, and professional soft skills through live interactive learning. The goal is not just to speak English, but to communicate confidently in every opportunity that matters." },
    ],
  },
  {
    key: "beyond",
    label: "+Beyond Programme",
    items: [
      { q: "What is the +Beyond Global Confidence Programme at Academy of Languages and Beyond (ALB)?", a: "The +Beyond Global Confidence Programme is Academy of Languages and Beyond's signature soft skills programme designed to complement language learning. It focuses on communication, public speaking, interview preparation, presentation skills, workplace readiness, networking, and professional confidence. The programme helps learners succeed not only in language exams but also in real academic, professional, and social environments." },
      { q: "Why does Academy of Languages and Beyond (ALB) include soft skills with language learning?", a: "Learning a language is only part of becoming globally confident. Many learners can understand a language but still struggle during interviews, presentations, meetings, or public speaking. Academy of Languages and Beyond (ALB) includes the +Beyond Global Confidence Programme to bridge this gap by helping students develop communication, confidence, and professional skills alongside language proficiency." },
      { q: "What soft skills are taught in the +Beyond Global Confidence Programme?", a: "The +Beyond Global Confidence Programme covers communication skills, public speaking, presentation techniques, interview preparation, workplace etiquette, professional networking, confidence building, teamwork, leadership fundamentals, and effective interpersonal communication. These skills prepare learners for success beyond the classroom." },
      { q: "Is the +Beyond Global Confidence Programme available online?", a: "Yes. The +Beyond Global Confidence Programme is delivered online through live interactive sessions, allowing learners to participate from anywhere. Just like Academy of Languages and Beyond (ALB)'s language programmes, the sessions focus on practical participation, discussions, activities, and real-world application rather than passive learning." },
      { q: "Can I join the +Beyond programme without learning a language?", a: "Yes. Academy of Languages and Beyond (ALB) also offers the +Beyond Global Confidence Programme as a standalone soft skills programme for learners and professionals who want to improve communication, interview performance, workplace confidence, and leadership skills." },
      { q: "Does Academy of Languages and Beyond (ALB) provide a certificate for the +Beyond Global Confidence Programme?", a: "Yes. Learners who successfully complete the +Beyond Global Confidence Programme receive a course completion certificate from Academy of Languages and Beyond (ALB), recognising their development in communication, confidence, and professional soft skills." },
      { q: "Who should join the +Beyond Global Confidence Programme?", a: "The programme is ideal for students preparing for higher education, working professionals aiming for career growth, job seekers, entrepreneurs, and anyone who wants to improve communication and professional confidence. Academy of Languages and Beyond (ALB) has designed +Beyond to support learners at different stages of their academic and professional journeys." },
      { q: "Will the +Beyond programme help me perform better in interviews?", a: "Yes. Interview preparation is one of the core components of the +Beyond Global Confidence Programme. Learners practise introductions, answering interview questions, professional communication, body language, and confidence-building exercises that prepare them for both academic and professional interviews." },
      { q: "Does the +Beyond programme include public speaking training?", a: "Yes. Public speaking forms an important part of the +Beyond Global Confidence Programme. Learners develop stage confidence, presentation delivery, storytelling techniques, audience engagement, and effective communication skills through guided activities and practical exercises." },
      { q: "Why is communication considered as important as language learning?", a: "Knowing a language does not automatically mean someone can communicate confidently. Real success often depends on the ability to express ideas clearly, present confidently, participate in discussions, and build meaningful relationships. Academy of Languages and Beyond (ALB) created the +Beyond Global Confidence Programme to ensure learners develop both language proficiency and the communication skills needed for lifelong success." },
    ],
  },
  {
    key: "exams",
    label: "Exams & Certifications",
    items: [
      { q: "Which language certification should I choose?", a: "The right language certification depends on your goals. If you're learning French, you may prepare for DELF, TEF, or TCF depending on whether your objective is higher education or immigration. German learners commonly pursue Goethe or TestDaF certifications, while English learners may prepare for IELTS depending on their academic or professional requirements. Academy of Languages and Beyond (ALB) helps every learner choose the certification that best aligns with their career, study abroad, or immigration plans." },
      { q: "What is the CEFR framework, and why is it important?", a: "The Common European Framework of Reference for Languages (CEFR) is the international standard used to measure language proficiency. It divides language learning into six levels—A1, A2, B1, B2, C1, and C2—making it easier for universities, employers, and governments worldwide to assess language ability. Academy of Languages and Beyond (ALB) structures its programmes according to CEFR, ensuring learners follow an internationally recognised progression." },
      { q: "Does Academy of Languages and Beyond (ALB) prepare students for international language exams?", a: "Yes. Academy of Languages and Beyond (ALB) prepares learners for internationally recognised language examinations through structured curricula, mock assessments, practical speaking practice, and exam-oriented guidance. Preparation is integrated into the learning journey while maintaining a strong focus on real-world communication." },
      { q: "Will I receive an internationally recognised certificate after completing my Academy of Languages and Beyond (ALB) course?", a: "Academy of Languages and Beyond (ALB) provides its own programme completion certificate upon successful completion of a course. For internationally recognised certifications such as DELF, Goethe, IELTS, TEF, or TCF, learners must appear for the official examination conducted by the respective authorised examination bodies. ALB prepares students for these exams but does not issue the official international certificates." },
      { q: "Does Academy of Languages and Beyond (ALB) help students register for official language examinations?", a: "Yes. Academy of Languages and Beyond (ALB) guides learners through the examination process by helping them understand eligibility requirements, examination formats, recommended preparation timelines, and available examination centres. The final registration is completed through the respective authorised examination authority." },
      { q: "How do I know when I am ready to take an international language exam?", a: "Academy of Languages and Beyond (ALB) regularly assesses learners through quizzes, assignments, mock examinations, classroom participation, and speaking evaluations. Based on your overall performance and proficiency, trainers recommend the most appropriate time to appear for an international certification exam." },
      { q: "Are international language certificates valid worldwide?", a: "Yes. Certifications such as DELF, Goethe-Zertifikat, IELTS, TEF, and TCF are recognised internationally by universities, employers, and government organisations. The exact recognition depends on the institution and country, but these certifications are widely accepted for education, employment, and immigration purposes." },
      { q: "Why should I prepare for international language exams through Academy of Languages and Beyond (ALB)?", a: "Academy of Languages and Beyond (ALB) goes beyond exam preparation by helping learners develop genuine communication skills alongside examination readiness. Through live instruction, speaking practice, structured assessments, and personalised guidance, learners gain the confidence needed not only to perform well in exams but also to use the language effectively in real-world situations." },
    ],
  },
  {
    key: "payments",
    label: "Payments & Fees",
    items: [
      { q: "Does Academy of Languages and Beyond (ALB) offer flexible payment options?", a: "Yes. Academy of Languages and Beyond (ALB) offers flexible payment options for many of its programmes. Available payment plans may vary depending on the course, duration, and ongoing enrolment period. Learners can contact the admissions team for the latest payment options." },
      { q: "Does Academy of Languages and Beyond (ALB) offer EMI facilities?", a: "Depending on the programme and payment partner availability, Academy of Languages and Beyond (ALB) may offer instalment or EMI options for eligible learners. Please contact the admissions team for current eligibility and payment plans." },
      { q: "Does Academy of Languages and Beyond (ALB) offer refunds?", a: "Academy of Languages and Beyond (ALB) follows a transparent refund policy. Refund eligibility depends on the programme, stage of enrolment, and the terms agreed upon at the time of admission. Learners are encouraged to review the official Refund Policy or speak with the admissions team before enrolling." },
      { q: "Are there any hidden charges at Academy of Languages and Beyond (ALB)?", a: "No. Academy of Languages and Beyond (ALB) believes in transparent pricing. Any applicable fees, programme inclusions, and optional examination costs are clearly communicated before enrolment so learners can make informed decisions." },
      { q: "Are examination fees included in the course fee?", a: "Official examination fees are generally charged separately by the respective examination authorities. Academy of Languages and Beyond (ALB) prepares learners for these examinations, while registration and examination charges are subject to the policies of the official certifying organisations." },
      { q: "Can I transfer my enrolment to another course?", a: "Course transfers may be possible depending on programme availability, timing, and academic suitability. Academy of Languages and Beyond (ALB) reviews such requests individually to ensure learners are placed in the most appropriate programme." },
    ],
  },
  {
    key: "verify",
    label: "Certificate Verification",
    items: [
      { q: "How can I verify an Academy of Languages and Beyond (ALB) certificate?", a: "Academy of Languages and Beyond (ALB) provides an online certificate verification system that allows employers, universities, and organisations to verify the authenticity of certificates issued by the academy. Simply enter the certificate details on the Certificate Verification page to confirm its validity." },
      { q: "Why should employers verify an Academy of Languages and Beyond (ALB) certificate?", a: "Certificate verification helps employers, educational institutions, and organisations confirm that a learner has successfully completed a programme at Academy of Languages and Beyond (ALB). It provides an additional layer of authenticity and trust during recruitment or admissions." },
      { q: "Can anyone verify an Academy of Languages and Beyond (ALB) certificate?", a: "Yes. Anyone with the required certificate details can use the official Academy of Languages and Beyond (ALB) Certificate Verification page to confirm the authenticity of a certificate issued by the academy." },
      { q: "What should I do if my certificate cannot be verified?", a: "If your certificate cannot be verified, first ensure that the certificate number and other required details have been entered correctly. If the issue persists, please contact Academy of Languages and Beyond (ALB) directly so the academic team can assist you in verifying your certificate." },
    ],
  },
];

/** Flattened list of every FAQ, for FAQPage JSON-LD. */
export const ALL_FAQS: FaqQA[] = FAQ_CATEGORIES.flatMap((c) => c.items);
